package Hotel.Rooms;

public enum RoomType {
    SINGLE(1),
    DOUBLE(2),
    FAMILY(4);

    private int capacity;

    //Constructor is Private, autogenerated for RoomType but we need to add one for the capacity.
    RoomType(int capacity) {
        this.capacity = capacity;
    }

    public int getCapacity() {
        return this.capacity;
    }

}
